config/routes.rb
Rails.application.routes.draw do
  resources :empleados
  resources :proyectos
  get 'personas/index'
  get 'personas/quienes_somos'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "menus#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  has_and_belongs_to_many :tareas
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
  has_many :tareas
  accepts_nested_attributes_for :tareas, allow_destroy: true
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  belongs_to :proyecto
  has_and_belongs_to_many :empleados
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre_completo)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    #code
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController

  def index
    @titulo2 = "En index 2"
    #render inline: "<h2>INGRESA CON HTML Y ESTILOS</h2>" # Utilizado para incorporar html en el controlador
    byebug
    redirect_to action: "quienes_somos", ingre: @titulo2
  end

  def quienes_somos
      @titulo = "Estamos en quienes_somos"
  end
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
    2.times { @proyecto.tareas.build }
  end



  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def proyecto_params
      params.require(:proyecto).permit(
        :nombre, :fecha_entrega, tareas_attributes: [
          :nombre, :prioridad, :_destroy
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/empleados/_form.html.erb
<%= form_for(empleado) do |f| %>
  <% if empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_completo %>
    <%= f.text_field :nombre_completo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Show', @empleado %> |
<%= link_to 'Back', empleados_path %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre completo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombre_completo %></td>
        <td><%= link_to 'Show', empleado %></td>
        <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>New Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Back', empleados_path %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre completo:</strong>
  <%= @empleado.nombre_completo %>
</p>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estudio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
ingresa a menus

app/views/personas/index.html.erb
<h1>Personas#index</h1>
<p>Find me in app/views/personas/index.html.erb</p>

app/views/personas/quienes_somos.html.erb
<h1><%= params[:ingre] %></h1>

app/views/proyectos/_form.html.erb
<%# app/views/proyectos/_form.html.erb %>
<%= nested_form_for(@proyecto) do |f| %>
  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% @proyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre, 'Nombre del proyecto' %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :fecha_entrega %><br>
    <%= f.date_select :fecha_entrega %>
  </div>
  <fieldset id="tareas">
    <%= f.fields_for :tareas %>
    <p><%= f.link_to_add "Agregar una tarea", :tareas %></p>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyectos/_tarea_fields.html.erb
<%# app/views/proyectos/_tarea_fields.html.erb %>
<div class="field">
  <%= f.label :nombre, 'Nombre de la tarea' %><br>
  <%= f.text_field :nombre %>
</div>
<div class="field">
  <%= f.label :prioridad %><br>
  <%= f.text_field :prioridad %>
</div>
<%= f.link_to_remove "Eliminar esta tarea" %>

app/views/proyectos/edit.html.erb
<h1>Editing Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyectos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha entrega</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <td><%= proyecto.nombre %></td>
        <td><%= proyecto.fecha_entrega %></td>
        <td><%= link_to 'Show', proyecto %></td>
        <td><%= link_to 'Edit', edit_proyecto_path(proyecto) %></td>
        <td><%= link_to 'Destroy', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyecto', new_proyecto_path %>

app/views/proyectos/new.html.erb
<h1>New Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Back', proyectos_path %>

app/views/proyectos/show.html.erb
<%# app/views/proyectos/show.html.erb %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @proyecto.nombre %>
</p>

<p>
  <strong>Fecha entrega:</strong>
  <%= @proyecto.fecha_entrega %>
</p>

<p>
  <strong>Tareas:</strong>
  <p>
    <% @proyecto.tareas.each do |tarea| %>
      Nombre: <%= tarea.nombre %><br/>
      Prioridad: <%= tarea.prioridad %>
      <hr/>
    <% end %>
  </p>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %><p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @proyecto.nombre %>
</p>

<p>
  <strong>Fecha entrega:</strong>
  <%= @proyecto.fecha_entrega %>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %>